Vagrant.configure("2") do |config|

  config.vm.define "proxy" do |proxy|
    proxy.vm.box = "centos7.1"
    proxy.vm.network "private_network", ip: "192.168.33.60"
    proxy.vm.synced_folder "./data/proxy", "/vagrant_data"
    proxy.vm.provision "shell", run: "always", inline: "systemctl restart network.service"
  end

  config.vm.define "web1" do |web1|
    web1.vm.box = "centos7.1"
    web1.vm.network "private_network", ip: "192.168.33.61"
    web1.vm.synced_folder "./data/web1", "/vagrant_data"
    web1.vm.provision "shell", run: "always", inline: "systemctl restart network.service"
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "centos7.1"
    web2.vm.network "private_network", ip: "192.168.33.62"
    web2.vm.synced_folder "./data/web2", "/vagrant_data"
    web2.vm.provision "shell", run: "always", inline: "systemctl restart network.service"
  end

end
